# Generated by Django 2.2.4 on 2019-10-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
    ]
