# Generated by Django 2.2.4 on 2019-10-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20191005_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='location',
            new_name='city',
        ),
    ]
