# Generated by Django 2.2.4 on 2019-10-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='donor',
            managers=[
            ],
        ),
    ]
